apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurequeue
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: accountName
    value: "rkacrstg"
  - name: accountKey
    secretKeyRef:
      name: localkey
      key: localkey
  - name: queueName
    value: "daprqueue"
auth:
  secretStore: daprkeyvault